trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'pipeline'
        appType: 'webAppLinux'
        WebAppName: 'jagruti-youtube-clone'
        packageForLinux: '$(System.DefaultWorkingDirectory)/build'
        RuntimeStack: 'DOTNETCORE:9.0'
        DeploymentTypeLinux: 'oneDeploy'
